<!DOCTYPE html>
<html>
<body>
<title> Register </title>
<p> Register an Account </p>

<?php if (isset($errorData) === true) : ?>
    <b>
        <?php echo 'There were error(s) creating your account!' ?>
    </b>
    <?php foreach ($errorData AS $errorKey => $errorSource) : ?>
        <?php foreach ($errorKey AS $errorNumber => $errorValue) : ?>
            <?php echo $errorSource . ': ' . $errorValue; ?>
            <br>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif; ?>


<form action="createaccount.php" method="POST">
    Username<input type="text" name="username" value="New User">
    <br>
    Password<input type="password" name="user_password" value="">
    <br>
    Confirm Password<input type="password" name="user_password_confirm" value="">
    <br>
    Email Address<input type="text" name="email_address" value="you@example.com">
    <br>
    <input type="hidden" name="token" value="<?php echo $csrfToken->getToken(); ?>">
    <input type="submit" value="Submit">
</form>


</body>
</html>
