<!DOCTYPE html>
<html>
<body>
<title> Register </title>
<p> Register an Account </p>

<form action="register.php" method="POST">
    Username<input type="text" name="user_name" value="New User">
    <br>
    Password<input type="password" name="user_password" value="">
    <br>
    Confirm Password<input type="password" name="user_password_confirm" value="">
    <br>
    Email Address<input type="text" name="email_address" value="you@example.com">
    <br>
    <input type="submit" value="Submit">
</form>


</body>
</html>
